{
 "title": "C-Chain",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "C-Chain Accepted Blocks in Last Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(avalanche_C_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "C-Chain Messages Received per Second",
   "type": "graph",
   "description": "Measures how many of each kind of message are received per second on the C-Chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Messages received/s" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_C_handler_pull_query_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_C_handler_push_query_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_C_handler_chits_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_C_handler_accepted_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_C_handler_put_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_C_handler_multi_put_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_C_handler_get_failed_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_C_handler_query_failed_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_C_handler_get_accepted_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_failed_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors failed"
    }
   ]
  },
  {
   "title": "C-Chain Processing Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avalanche_C_processing{job=\"avalanchego\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "C-Chain Percentage of Successful Queries",
   "type": "graph",
   "description": "Percentage of queries for which we receive chits on time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(avalanche_C_handler_chits_count{job=\"avalanchego\"}[2m]) + 1) / (increase(avalanche_C_handler_chits_count{job=\"avalanchego\"}[2m]) + increase(avalanche_C_handler_query_failed_count{job=\"avalanchego\"}[2m]) + 1)"
    }
   ]
  },
  {
   "title": "C-Chain Message Handling Time (Total)",
   "type": "graph",
   "description": "Measures how much of each second is being spent handling different kinds of messages on the C-Chain.\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "seconds/second" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_C_handler_pull_query_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_C_handler_push_query_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_C_handler_chits_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_C_handler_accepted_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_C_handler_put_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_C_handler_multiput_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_C_handler_get_failed_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_C_handler_query_failed_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_C_handler_get_accepted_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_failed_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors failed"
    }
   ]
  },
  {
   "title": "C-Chain Message Handling Time (per Message)",
   "type": "graph",
   "description": "Measures how long each kind of request on the C-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_C_handler_pull_query_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_pull_query_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_C_handler_push_query_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_push_query_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_C_handler_chits_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_chits_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_C_handler_accepted_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_accepted_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_get_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_C_handler_put_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_put_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_C_handler_multiput_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_multi_put_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_get_ancestors_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_C_handler_get_failed_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_get_failed_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_C_handler_query_failed_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_query_failed_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_C_handler_get_accepted_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_get_accepted_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_failed_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_get_ancestors_failed_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors failed"
    }
   ]
  },
  {
   "title": "Incoming Messages Dropped in Last Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(avalanche_C_handler_dropped[1m])"
    }
   ]
  },
  {
   "title": "Unprocessed Incoming Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avalanche_C_handler_pending", "legendFormat": "Pending Messages" }
   ]
  }
 ]
}