{
 "title": "Database",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Operations per second",
   "type": "graph",
   "description": "Measures how many of each database operation is performed each second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_db_put_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_db_get_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_db_delete_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(avalanche_db_has_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(avalanche_db_compact_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(avalanche_db_batch_put_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(avalanche_db_batch_delete_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(avalanche_db_batch_reset_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(avalanche_db_batch_replay_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "batch replay"
    },
    {
     "expr": "rate(avalanche_db_iterator_key_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "iterator key"
    },
    {
     "expr": "rate(avalanche_db_iterator_value_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "iterator value"
    }
   ]
  },
  {
   "title": "% of time spent on operations",
   "type": "graph",
   "description": "Measures what percentage of each second is being spent on different database operations",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "Percent of time" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_db_put_sum{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_db_get_sum{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_db_delete_sum{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(avalanche_db_has_sum{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "has"
    },
    {
     "expr": "rate(avalanche_db_compact_sum{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(avalanche_db_batch_put_sum{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(avalanche_db_batch_delete_sum{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(avalanche_db_batch_reset_sum{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(avalanche_db_batch_replay_sum{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "batch replay"
    },
    {
     "expr": "rate(avalanche_db_iterator_key_sum{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "iterator key"
    },
    {
     "expr": "rate(avalanche_db_iterator_value_sum{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "iterator value"
    }
   ]
  },
  {
   "title": "Time per operation",
   "type": "graph",
   "description": "Measures the time, in seconds, each operation takes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_db_put_sum{job=\"avalanchego\"}[1m])/rate(avalanche_db_put_count{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_db_get_sum{job=\"avalanchego\"}[1m])/rate(avalanche_db_get_count{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_db_delete_sum{job=\"avalanchego\"}[1m])/rate(avalanche_db_delete_count{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(avalanche_db_has_sum{job=\"avalanchego\"}[1m])/rate(avalanche_db_has_count{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "has"
    },
    {
     "expr": "rate(avalanche_db_compact_sum{job=\"avalanchego\"}[1m])/rate(avalanche_db_compact_count{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(avalanche_db_batch_put_sum{job=\"avalanchego\"}[1m])/rate(avalanche_db_batch_put_count{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(avalanche_db_batch_delete_sum{job=\"avalanchego\"}[1m])/rate(avalanche_db_batch_delete_count{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(avalanche_db_batch_reset_sum{job=\"avalanchego\"}[1m])/rate(avalanche_db_batch_reset_count{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(avalanche_db_batch_replay_sum{job=\"avalanchego\"}[1m])/rate(avalanche_db_batch_replay_count{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "batch replay"
    },
    {
     "expr": "rate(avalanche_db_iterator_key_sum{job=\"avalanchego\"}[1m])/rate(avalanche_db_iterator_key_count{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "iterator key"
    },
    {
     "expr": "rate(avalanche_db_iterator_value_sum{job=\"avalanchego\"}[1m])/rate(avalanche_db_iterator_value_count{job=\"avalanchego\"}[1m])/10000000",
     "legendFormat": "iterator value"
    }
   ]
  }
 ]
}